# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Newspicel.SDRminusminus
PackageVersion: 1.8.1
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- sdrmm-desktop
ProductCode: SDR--
ReleaseDate: 2026-09-29
AppsAndFeaturesEntries:
- Publisher: newspicel
  ProductCode: SDR--
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\SDR--'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Newspicel/sdrminusminus/releases/download/v1.8.1/SDR--_1.8.1_x64-setup.exe
  InstallerSha256: 31F5085BB8D22B418A711462294A5FC520586D031D754CC110DC30275F4F72DB
- Architecture: arm64
  InstallerUrl: https://github.com/Newspicel/sdrminusminus/releases/download/v1.8.1/SDR--_1.8.1_arm64-setup.exe
  InstallerSha256: 20732C0E0556E6A2313475AD945803C98F410FA941DEC54367DFD399B892614C
ManifestType: installer
ManifestVersion: 1.12.0
