# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Newspicel.SDRmm
PackageVersion: 2.0.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- sdrmm-desktop
ProductCode: SDR--
ReleaseDate: 2026-10-01
AppsAndFeaturesEntries:
- Publisher: newspicel
  ProductCode: SDR--
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\SDR--'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Newspicel/sdrmm/releases/download/v2.0.0/SDR--_2.0.0_x64-setup.exe
  InstallerSha256: 43D36FDF905EAC409C9A81E6CE339F30CE3A0E3DF16F923092065E7CC14B6A23
- Architecture: arm64
  InstallerUrl: https://github.com/Newspicel/sdrmm/releases/download/v2.0.0/SDR--_2.0.0_arm64-setup.exe
  InstallerSha256: 9C107CB6E5F09AEE926698BBDEB272D1F565A48940AE805ACA21FDBC8FEAF1B8
ManifestType: installer
ManifestVersion: 1.12.0
