# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Newspicel.SDRminusminus
PackageVersion: 1.9.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- sdrmm-desktop
ProductCode: SDR--
ReleaseDate: 2026-09-30
AppsAndFeaturesEntries:
- Publisher: newspicel
  ProductCode: SDR--
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\SDR--'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Newspicel/sdrminusminus/releases/download/v1.9.0/SDR--_1.9.0_x64-setup.exe
  InstallerSha256: 4A01041AABC484BFEE7B83DEF93037A9BC4DE091E4A81A2CD3DDE046002B8D0F
- Architecture: arm64
  InstallerUrl: https://github.com/Newspicel/sdrminusminus/releases/download/v1.9.0/SDR--_1.9.0_arm64-setup.exe
  InstallerSha256: 11F75B989253B9AA3C1AFEA8F140A3A95A769E1EE71A7B26B2ADE62E2AF6F8FF
ManifestType: installer
ManifestVersion: 1.12.0
